version: '3.8'

networks:
  laravel:
    name: laravel
    
volumes:
  src-laravel:

services:
  php:
    image: php:8.1.22-fpm
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=lamsolusi
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    networks:
      - laravel

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "4280:80"
    volumes:
      - src-laravel:/var/www/html/
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel